---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssd-claim-pihole
  namespace: home
  annotations:
    nfs.io/storage-path: "pihole"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
