---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: assistant-claim-config
  namespace: home
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: assistant-claim-time
  namespace: home
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
