---
apiVersion: v1
kind: Service
metadata:
  name: assistant-service
  namespace: home
spec:
  selector:
    app: assistant
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: assistant-http
