---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssd-claim-prometheus
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi
