---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssd-claim-grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
