---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
  namespace: monitoring
data:
  grafana.ini: |
    [server]
      protocol = http
      http_port = 3000
    [auth.anonymous]
      enabled = false
    [analytics]
      reporting_enabled = false
      check_for_updates = false
    [log]
      mode = console
      level = info
    [paths]
      data = /var/lib/grafana/data
      plugins = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning
      logs = /var/log/grafana
    [security]
      disable_gravatar = true
