---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    app: grafana
  namespace: monitoring
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - access: proxy
        editable: true
        isDefault: true
        name: Prometheus
        orgId: 1
        version: 1
        type: prometheus
        url: http://prometheus-service.monitoring.svc:9090
