repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks protect --staged --verbose
        language: system
        pass_filenames: false
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: system
        files: ^ansible/.*\.ya?ml$
