---
- name: Enable cgroups in cmdline.txt
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^((?!.*cgroup_memory=1 cgroup_enable=memory).*)$'
    replace: '\1 cgroup_memory=1 cgroup_enable=memory'
  register: common_cgroup_config
  notify: Reboot nodes

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
  loop:
    - net.ipv6.conf.all.forwarding
    - net.ipv6.conf.default.forwarding

- name: Install k3s dependencies
  ansible.builtin.apt:
    name:
      - curl
      - iptables
    state: present
