---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: automation
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: xxxxxx
  DB_POSTGRESDB_DATABASE: n8n
  DB_POSTGRESDB_USER: n8n
  DB_POSTGRESDB_PASSWORD: xxxxxx
  DB_ROOT_PASSWORD: xxxxxx
