---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-n8n
  namespace: automation
  annotations:
    nfs.io/storage-path: "n8n"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
