---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: storage
data:
  engine_mysql_database: nextcloud
  engine_admin_user: alireza
  engine_trusted_domains: localhost https://drive.example.io
  engine_smtp_host: smtppro.zoho.com
  engine_smtp_port: '465'
  engine_smtp_secure: ssl
  engine_smtp_name: alireza@example.io
  engine_mail_from: alireza
  engine_mail_domain: example.io
  engine_overwrite_cli_url: https://drive.example.io
  engine_overwrite_protocol: https
  engine_overwrite_host: drive.example.io
  engine_forwarded_headers: X-Forwarded-For HTTP_X_FORWARDED_FOR
  engine_trusted_proxies: 192.168.178.201 192.168.178.202 192.168.178.203 192.168.178.204
