---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-nextcloud
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1000Gi
