---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  labels:
    app: nextcloud
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nfs-pvc-nextcloud
      containers:
        - name: nextcloud
          image: nextcloud
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html
              subPath: storage
          env:
            - name: REDIS_HOST
              value: 127.0.0.1
            - name: MYSQL_HOST
              value: 127.0.0.1
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_mysql_database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: engine_mysql_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: engine_mysql_password
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_admin_user
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: engine_admin_password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_trusted_domains
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_smtp_host
            - name: SMTP_SECURE
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_smtp_secure
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_smtp_port
            - name: SMTP_NAME
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_smtp_name
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: engine_smtp_password
            - name: MAIL_FROM_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_mail_from
            - name: MAIL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_mail_domain
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_trusted_proxies
            - name: OVERWRITEHOST
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_overwrite_host
            - name: OVERWRITEPROTOCOL
              valueFrom:
                confiMapKeyRef:
                  name: nextcloud-config
                  key: engine_overwrite_protocol
            - name: OVERWRITECLIURL
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_overwrite_cli_url
            - name: APACHE_DISABLE_REWRITE_IP
              value: "1"
        - name: mysql
          image: mariadb
          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/lib/mysql
              subPath: database
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: engine_mysql_username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: engine_mysql_password
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "1"
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: engine_mysql_database
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
