---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssd-claim-paperless
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 150Gi
