apiVersion: batch/v1
kind: CronJob
metadata: 
    name: nextcloud-cronjob
    namespace: storage
spec: 
    schedule: "*/5 * * * *"
    jobTemplate:
      spec:
        template: 
          spec: 
            containers:
              - name: cron-runner
                image: busybox
                imagePullPolicy: IfNotPresent
                command:
                - /bin/sh
                - -c
                - wget https://drive.example.io/cron.php
            restartPolicy: OnFailure
